# Generated by Django 4.2.6 on 2024-01-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_userone_user_identifier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserONe',
        ),
    ]
